version: '3.8'

services:
  packagedownloader:
    image: packagedownloader
    build:
      context: .
      dockerfile: DOCKERFILE
    ports:
      - "5000:80"
    environment:
      - AI__API_KEY=${AI__API_KEY}
    restart: always