/**
 * @typedef {'search' | 'versions'} EndpointKind
 * A logical backend operation exercised by the load test.
 */

/**
 * @typedef {Object} ProviderCase
 * @property {string} provider PackageType value accepted by the backend.
 * @property {EndpointKind} kind Logical endpoint category.
 * @property {string} value Search text or exact package identifier.
 * @property {string} name Stable metric name that avoids high-cardinality URL tags.
 */

/**
 * @typedef {Object} LoadConfiguration
 * @property {string} baseUrl Backend URL without a trailing slash.
 * @property {string} buildLabel Label written to metrics and comparison reports.
 * @property {string} profile Selected execution profile: smoke, load, or stress.
 * @property {number} rate Iterations started per second by arrival-rate profiles.
 * @property {string} duration Duration accepted by k6, for example `2m`.
 * @property {number} preAllocatedVUs Initial virtual-user pool.
 * @property {number} maxVUs Maximum virtual-user pool.
 * @property {number} maxVersions Maximum number of versions requested from the API.
 * @property {string} resultFile Path of the compact JSON summary generated by k6.
 * @property {boolean} includeDocker Whether Docker Hub cases are enabled.
 */

/**
 * Reads a positive integer environment variable and falls back when it is absent or invalid.
 *
 * @param {string} name Environment variable name.
 * @param {number} fallback Value returned for missing and invalid input.
 * @returns {number} Parsed positive integer.
 */
function positiveInteger(name, fallback) {
    const parsed = Number.parseInt(__ENV[name] || '', 10);
    return Number.isInteger(parsed) && parsed > 0 ? parsed : fallback;
}

/**
 * Normalizes a backend URL so request builders can safely append absolute API paths.
 *
 * @param {string} value Raw URL from the environment.
 * @returns {string} URL without trailing slash characters.
 */
function normalizeBaseUrl(value) {
    return value.replace(/\/+$/, '');
}

/** @type {number} Initial VU pool parsed once so maxVUs can never be smaller. */
const preAllocatedVUs = positiveInteger('PRE_ALLOCATED_VUS', 4);

/** @type {LoadConfiguration} */
export const config = Object.freeze({
    baseUrl: normalizeBaseUrl(__ENV.TARGET_URL || 'http://127.0.0.1:5093'),
    buildLabel: __ENV.BUILD_LABEL || 'local',
    profile: (__ENV.PROFILE || 'smoke').toLowerCase(),
    rate: positiveInteger('RATE', 2),
    duration: __ENV.DURATION || '1m',
    preAllocatedVUs,
    maxVUs: Math.max(preAllocatedVUs, positiveInteger('MAX_VUS', 20)),
    maxVersions: positiveInteger('MAX_VERSIONS', 40),
    resultFile: __ENV.RESULT_FILE || 'results/local.json',
    includeDocker: (__ENV.INCLUDE_DOCKER || 'false').toLowerCase() === 'true',
});

/** @type {ReadonlyArray<ProviderCase>} */
const defaultCases = Object.freeze([
    { provider: 'Npm', kind: 'search', value: 'react', name: 'npm_search' },
    { provider: 'Nuget', kind: 'search', value: 'json', name: 'nuget_search' },
    { provider: 'VsCode', kind: 'search', value: 'python', name: 'vscode_search' },
    { provider: 'Npm', kind: 'versions', value: 'react', name: 'npm_versions' },
    { provider: 'Nuget', kind: 'versions', value: 'Newtonsoft.Json', name: 'nuget_versions' },
    { provider: 'VsCode', kind: 'versions', value: 'ms-python/python', name: 'vscode_versions' },
]);

/** @type {ReadonlyArray<ProviderCase>} */
const dockerCases = Object.freeze([
    { provider: 'Docker', kind: 'search', value: 'nginx', name: 'docker_search' },
    { provider: 'Docker', kind: 'versions', value: 'nginx', name: 'docker_versions' },
]);

/**
 * Returns the stable provider rotation used by every comparison run.
 * Docker is opt-in because one unified Docker search fans out to multiple Docker Hub calls.
 *
 * @returns {ReadonlyArray<ProviderCase>} Enabled provider requests.
 */
export function getProviderCases() {
    return config.includeDocker ? Object.freeze(defaultCases.concat(dockerCases)) : defaultCases;
}

/**
 * Creates the k6 scenario for the selected profile.
 * Smoke performs exactly one pass over all cases; load and stress use open-model arrival rates.
 *
 * @param {number} caseCount Number of enabled provider cases.
 * @returns {Object} k6 scenarios configuration.
 */
export function createScenarios(caseCount) {
    if (config.profile === 'smoke') {
        return {
            provider_smoke: {
                executor: 'shared-iterations',
                vus: 1,
                iterations: caseCount,
                maxDuration: '2m',
                exec: 'providerRequest',
                tags: { profile: 'smoke', build: config.buildLabel },
            },
        };
    }

    if (config.profile === 'stress') {
        return {
            provider_stress: {
                executor: 'ramping-arrival-rate',
                startRate: 1,
                timeUnit: '1s',
                preAllocatedVUs: config.preAllocatedVUs,
                maxVUs: config.maxVUs,
                stages: [
                    { target: config.rate, duration: '30s' },
                    { target: config.rate, duration: config.duration },
                    { target: 0, duration: '15s' },
                ],
                gracefulStop: '30s',
                exec: 'providerRequest',
                tags: { profile: 'stress', build: config.buildLabel },
            },
        };
    }

    if (config.profile !== 'load') {
        throw new Error(`Unsupported PROFILE '${config.profile}'. Use smoke, load, or stress.`);
    }

    return {
        provider_load: {
            executor: 'constant-arrival-rate',
            rate: config.rate,
            timeUnit: '1s',
            duration: config.duration,
            preAllocatedVUs: config.preAllocatedVUs,
            maxVUs: config.maxVUs,
            gracefulStop: '30s',
            exec: 'providerRequest',
            tags: { profile: 'load', build: config.buildLabel },
        },
    };
}
