name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install npm dependencies
      run: cd Frontend/package-downloader-react && npm install && cd -

    - name: Build frontend
      run: npm run build --prefix "Frontend/package-downloader-react"

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.x'

    - name: Restore NuGet packages
      run: dotnet restore Backend/PackageDownloader.API

    - name: Build backend
      run: dotnet build --configuration Release --no-restore Backend/PackageDownloader.API

    - name: Test backend
      run: dotnet test --no-build --verbosity normal Backend/PackageDownloader.API


  deploy:
    runs-on: app-host

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and run app docker container
        run: chmod +x ./start.sh && ./start.sh       
      
      