name: Test app

on:

  pull_request:
    branches:
      - master
    types:
      - opened

jobs:
  build-and-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v6

    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: '26.5.1'
        cache: 'npm'
        cache-dependency-path: Frontend/package-downloader-react/package-lock.json

    - name: Setup npm
      run: npm install --global npm@12.0.2

    - name: Install npm dependencies
      run: npm ci --prefix "Frontend/package-downloader-react"

    - name: Build frontend
      run: npm run build --prefix "Frontend/package-downloader-react"

    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: '10.0.x'

    - name: Restore NuGet packages
      run: dotnet restore Backend/PackageDownloader.API

    - name: Build backend
      run: dotnet build --configuration Release --no-restore Backend/PackageDownloader.API

    - name: Test backend
      run: dotnet test --no-build --verbosity normal Backend/PackageDownloader.API
      
